name: 'OpenPubKey Signer'
description: 'Sign stuff with OpenPubKey on GitHub actions'
inputs:
  message:
    description: 'String to sign (e.g. image digest, attestation etc...)'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.message }}
